[phases.install]
cmds = ["NPM_CONFIG_PRODUCTION=false npm ci --include=dev"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "if [ ! -f .medusa/client/index.html ]; then npm run build; fi; medusa start"